### ISSUE TITLE
Duck DNS is not renewing expired certificate

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [home-assistant/hassio-addons#1217]
I have Duck DNS 1.11
Google Chrome show certificate from Let's Encrypt is expired March 21
But Duck DNS says
```
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[20:00:51] INFO: OK
------ip-----
NOCHANGE
# INFO: Using main config file /data/workdir/config
Processing gavrhome.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till May 20 20:07:53 2020 GMT Certificate will not expire
(Longer than 30 days). Skipping renew!
[20:06:00] INFO: OK
-------ip-----
NOCHANGE
```

**Comment by mpigsley** [comment]
Same here for me. Looks like mine says it's set to expire 2 months from when it actually expired as well.

**Comment by ludeeus** [comment]
It does not renew since it identifies the cert as valid.
Make sure you use the correct values in the configuration of the service using the certificate.

**Comment by mpigsley** [comment]
Yup, correct values have been used. In fact, nothing has changed in the configuration since I set it up initially.

**Comment by ludeeus** [comment]
Try checking it with this:
```bash
openssl x509 -enddate -noout -in /ssl/fullchain.pem
```

And make sure you only have 2 files in the /ssl directory

**Comment by mpigsley** [comment]
Looks like the hassio CLI does not have the openssl command? Can I install that somehow?

**Comment by ludeeus** [comment]
Use the community SSH addon (not sure if the default has it)

**Comment by mpigsley** [comment]
Yeah, I've SSH'ed on with the "Terminal & SSH" add-on. Is that the one you're referring to?

**Comment by ludeeus** [comment]
No, that is the default one.
This is the one I meant:
![image](https://user-images.githubusercontent.com/15093472/79072034-247dd900-7cdf-11ea-908d-8bfb5fa44015.png)

**Comment by mpigsley** [comment]
Ah, okay so it says it expired on April 6th which is in-line with the expired cert in the browser. Here's my config and output for the Duck DNS add-on:

```
lets_encrypt:
  accept_terms: true
  certfile: /ssl/fullchain.pem
  keyfile: /ssl/privkey.pem
token: **
domains:
  - **.duckdns.org
seconds: 300
```

```
# INFO: Using main config file /data/workdir/config
Processing **.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jun  6 08:42:00 2020 GMT Certificate will not expire
(Longer than 30 days). Skipping renew!
```

**Comment by ludeeus** [comment]
Ah!
```
  certfile: /ssl/fullchain.pem
  keyfile: /ssl/privkey.pem
```
That will place the updated certs in `/ssl/ssl/*.pem`, and not where you use/checked it `/ssl/*.pem`

**Comment by mpigsley** [comment]
Ahh, okay, so I removed `/ssl/` from both the cert and key file, restarted it, and it's still stating Jun 6th as the expiration date.

It looks like there are some symlink shenanigans going on between `/root/ssl` and `/ssl` so maybe there is a directory there that I just can't see?

**Comment by mpigsley** [comment]
I had to reinstall the duckdns addon, which generated a new cert, and restart home assistant, and now it's working as expected. Thanks for your help @ludeeus!

**Comment by frenck** [comment]
Thanks for letting us know your problem is resolved @mpigsley 👍

**Comment by sergey-koba-mobidev** [comment]
So my problem still exists
```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: *
domains:
  - *.duckdns.org
seconds: 300
```

I can reinstall Duck DNS and it will definitely fix the problem. But not the cause of the issue.
Would you like me to debug something before I reinstall duck dns?

**Comment by KBrownConsulting** [comment]
@sergey-koba-mobidev I'm guessing you were running into the same issue I did. See here: #1280

**Comment by sergey-koba-mobidev** [comment]
Thx @KBrownConsulting  looks like that Hassio restart helped

**Comment by donnlee** [comment]
I also had to restart Home Assistant to force the certificate renewal.

**Comment by akmolina28** [comment]
I'm having this issue today. I uninstall/reinstall the addon and force it to recreate the certificate, but it seems like Let's Encrypt is not updating.

Here are the logs from my addon:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Generating account key...
+ Registering account key with ACME server...
+ Fetching account ID...
+ Done!
[17:59:19] INFO: OK
68.1.53.206
NOCHANGE
[17:59:19] INFO: Renew certificate for domains: ######.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing ######.duckdns.org
 + Creating new directory /data/letsencrypt/######.duckdns.org ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for ######.duckdns.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
OK + Responding to challenge for ########.duckdns.org authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
OK + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
 + Done!
[18:04:28] INFO: OK
68.1.53.206
NOCHANGE
```

And here is the certificate from Let's Encrypt, showing an expiry date of March 29.


![image](https://user-images.githubusercontent.com/2997206/113363082-8c289c00-9315-11eb-930a-b30e08f13a34.png)


I can't tell if this is a problem with the addon or if it's Let's Encrypt not updating the cert correctly.
