### ISSUE TITLE
Urgent! HASS not seeing DeconZ entities anymore after latest add-on update

### ISSUE THREAD

**Issue by Flight777** [home-assistant/hassio-addons#1377]
I just did the update of the Deconz add-on to 5.3.5. After reading the changelog, it was actually a downgrade though?

However, now HASS is not able to connect to any of the DeconZ entities anymore, while in Phoscon they are all there and work. So something is wrong with the latest update of the add-on and it breaks it connection somehow to HASS (integration still shows up and is not removed).

I've rebooted the HASS server in it's entirety as well, but the entities in HASS do not connect back and show as unavailable. 

Only error I see in the log so far:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:423
First occurred: 5:24:57 PM (2 occurrences)
Last logged: 5:32:12 PM

Unable to find referenced entities light.attic_light_5, light.attic_light_6, light.attic_light_7, light.attic_light_8
Unable to find referenced entities cover.window_covering_device_18, cover.window_covering_device_19
```

In the supervisor I do see the following (which is the docker IP of Deconz):

```
20-06-04 16:06:47 ERROR (SyncWorker_9) [asyncio] Unclosed connection
client_connection: Connection<ConnectionKey(host='172.30.33.1', port=8099, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>
```

How can I best troubleshoot to provide some more useful info?

It's quite urgent because almost all lights in our house are running on Zigbee and cannot be controlled now....

**Comment by alexdepalex** [comment]
Same here. I still see my devices in Phoscon, but only a small amount (<5%) is connected. Checked on the Deconz Discord and they say this happens if you downgrade. Don't know how to fix this, but a *warning* in the change log is appreciated next time.

I tried to restore a snapshot, but that didn't help and even corrupted my MySQL database because the backup process apparently isn't creating consistent backups.

**Comment by MYLE-01** [comment]
same here can HA can control and see the stuff but no web page

![image](https://user-images.githubusercontent.com/4362345/83834228-e252a000-a741-11ea-859e-3f10f1cf04ae.png)

door sensor are all working

**Comment by jordibsk10** [comment]
Same here. Not working since last update (the prior version was working fine). This is what I get now:

![image](https://user-images.githubusercontent.com/62246724/83839490-7bf75e80-a6fc-11ea-95f6-54c73b3d75fa.png)

**Comment by MYLE-01** [comment]
Current version: 5.3.5
 mine working now

![image](https://user-images.githubusercontent.com/4362345/83841616-4f236580-a755-11ea-8361-6eab2ef2ce6f.png)

I DID NOTHING

**Comment by Flight777** [comment]
In the end I've fixed it by removing and adding the integration again, had to go manual through some entities to set them correct though because some slightly deviated over time with the DeconZ name.

But definitely something went wrong with the update and if this would have been a known issue of a downgrade as one of the above people pointed out, maybe indeed a fat warning in the changelog would help next time? Because on my end everything was working fine before.

**Comment by Isotope1** [comment]
After my deCONZ functionality was destroyed about a week ago, I decided to do a clean install of Home Assistant.  I continue to have deCONZ issues.  Critically, when sensors or lights are added, they do not appear in Home Assistant (i.e., don't show under the states pane).

**Comment by christian1986** [comment]
For me the lights stop to work, but all motion sensors are still working. To resolve it I then delete the integration and add it again and all is back, working as it should

**Comment by jappish84** [comment]
I´m having the same issue, all devices are present and working in the phoscon app. I´m seeing proper ID reported and HW detected i HA. Only way to get the entities accessible in HA is to remove the integration, and readd it, but the entities disappear from HA on a HA restart again. This has been an issue for me for at least the latest two versions.

**Comment by DaveRuijter** [comment]
The issues I experienced are solved with the latest update (not sending events to HA).

**Comment by jappish84** [comment]
I updated to 0.112.3 today and it seems the issues are gone, a little too soon to tell

**Comment by jappish84** [comment]
Unfortunately the issue is still present, I can see and control all devices through Phoscon app, but they are unavailable in HA

**Comment by Mimiix** [comment]
@jappish84 Do you still have the issue?

**Comment by jappish84** [comment]
@Mimiix yeah, unfortunately I think I still do, I just updated to 0.113.1 and latest deconz and initially after update the issue was present, and I could resolve it the usual way by removing the integration and readding it.

Everything is working now, but I thought I'd give it some time and a couple of reboots before saying the issues are gone

**Comment by Mimiix** [comment]
Thanks for the ping Ludeeus :) 

@jappish84 You might be able to use the  deconz.device_refresh service to make it working again.

**Comment by christian1986** [comment]
The only way I can get it working again is deleting the integration and re-adding it.

**Comment by ludeeus** [comment]
This sounds like an issue with the integration and not the addon.
This issue should probably be closed and you should open an issue in home-assistant/core for the `deconz` integration instead.

**Comment by Mimiix** [comment]
@ludeeus I just pmed you about this on Discord ;)

**Comment by ludeeus** [comment]
Sure, but that is for something else.
> I could resolve it the usual way by removing the integration and readding it.

Indicates that the addon is working, but the integration loses its connection.
If there was an issue with the addon at that point, readding the integration would not help.

**Comment by jappish84** [comment]
> Thanks for the ping Ludeeus :)
> 
> @jappish84 You might be able to use the deconz.device_refresh service to make it working again.

Thanks, I'll try that next time, I haven't had any issues since my latest reply BTW. 

@ludeeus not sure where the line between the add-on and integration is, but just a friendly reminder that deconz is working and devices are connected, just marked as not available in home assistant

**Comment by lbouriez** [comment]
Hello, same issue since the last update.
Everything works in deconz but in HA the lights are not available.

**Comment by jappish84** [comment]
Unfortunately the issue is still present. I have all devices controllable through Phoscon app, but they are marked as unavailable in HA. Simply removing the integration, restarting HA and re-adding the integration temporarily solves the issue

**Comment by lbouriez** [comment]
> Unfortunately the issue is still present. I have all devices controllable through Phoscon app, but they are marked as unavailable in HA. Simply removing the integration, restarting HA and re-adding the integration temporarily solves the issue 

But are you not losing all your device doing like this ?
I have too much ZigBee device and I don't want to mess it up :/

**Comment by jappish84** [comment]
Fortunately all devices are named the same and no the deconz addon is untouched, so no device reconfiguration is necessary

**Comment by lbouriez** [comment]
It didn't work for me, now the light are completely missing from HA, I am missing the 30 light entities XD
From Deconz, everything still there and working.

**Comment by MrSolo570** [comment]
did this ever get fixed? because right now I have the exact same issue: two sensors work perfectly fine with deconz/phoscon, but Home Assistant does not see any sensor entities...

**Comment by jappish84** [comment]
Well, I haven't had this issue for years. What version are you running @MrSolo570?

**Comment by MrSolo570** [comment]
Still trying to figure this out. Deleting and re-adding the complete integration didnt do the trick either. After that lot of my other entites were gone (because I think they got renamed, so a lot of automations broke) and still, the sensor in question didnt work. Right now i am trying to go back and restore a back-up, see if that does the trick. I - was - on latest deconz plugin and latest home assistant version 2023.7.2

**Comment by dagord** [comment]
Hello.
I'm experiencing the same issue after migrating from a Raspberry to a NUC. I reimported the last backup and I'm encountering issues with zigbee devices: I have 26 (ligths and sensors) and only lights came up immediately in Phoscon, while sensors took up to 2 hourse to connect. Moreover, Hassio cannot see them anymore. I tried switching USB cable, USB port, zigbee channel and even reinstall integration... nothing works
