### ISSUE TITLE
Samba stopped working after Windows 10 update

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/hassio-addons#1437]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Can't access Homeassistant via my windows 10 machines (tried on two different computers) and Samba addon after 1903 update.

## Environment
Android devices working correctly, two windows 10 machines can not access my HA through samba.  They can ping, tracert, etc. Just not samba.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bpwats** [comment]
Win 10 does not enable SMBv1 anymore, since it has been insecure. This happened to me with a May 2020 fresh install. When the required steps are taken to enable SMB protocol v1, your shares will be found again, including home ass / Apple TineMachine etc. Probably it is better for home ass to disable protocol version 1 by default, in favor of version 2 or 3. On Apple TimeMachine this is not possible (obsolete device).

**Comment by bschatzow** [comment]
I wish this was the problem.  SMBv1 is enabled.  I tried disabling it, then re-adding it. No difference.  I looked at several threads in the forums and it seems I am not the only one where it works, then stops working.  It maybe a windows 10 issue.  Not sure yet.  Don't understand why Home Assistant is not using version 2 or 3.  On another issue with Samba, I do have an NAS that says it supports two and three.  It will not work with windows without SMB 1 installed.  Could be MS not following their own specs?

**Comment by bschatzow** [comment]
> Sorry, this is the wrong repo, you should create an issue in the repo for the Samba addon.
> 
> https://github.com/home-assistant/hassio-addons

You closed it and then reopened.  Do I move the but to the above?

**Comment by bramkragten** [comment]
I moved it for you.

**Comment by msap6** [comment]
Go to Control Panel > Program & Features > Turn Windows features on or off > look for SMB 1.0/CIFS Sharing support and enable it.
try adding network location in my computer.

**Comment by bschatzow** [comment]
Already on.  Something else changed

**Comment by msap6** [comment]
try adding network location in my computer. i resolved with it

**Comment by bschatzow** [comment]
That did not solve it for me, but it is working again.  Changed to many things (to really know what the issue was) I .e network settings, uninstalled SMB1, reinstalled, winsock reset, ip flush, etc. but it is now working.  This should not be this difficult.  I had one NAS working with Samba2/3 support and suddenly lost my Home Assistant with Samba V1.  I'm sure Microsoft changed something in the update that caused the issue (maybe plugged some security hole in V1?  I don't know.  Maybe it is time for the home assistant Samba to update to a newer more secure version?  In any case, thanks.
