### ISSUE TITLE
Allow secrets in 'Samba share' addon config

### ISSUE THREAD

**Issue by CodeFinder2** [home-assistant/hassio-addons#682]
Hi,
first of all: great work.
Even in the latest version 8.1, secrets are not supported in the addon's config. Would be great if secrets would be allowed and/or if the auth data would be retrieved from Home Assistant (like Mosquitto does it).

Kind regards!

**Comment by frenck** [comment]
This has been resolved by the latest supervisor, all add-ons now support the use of secrets! 🎉

**Comment by mrchief** [comment]
> This has been resolved by the latest supervisor

For the uninitiated, what's a "latest supervisor"? I installed HassOS 3.7 today on Raspberry Pi 3 but I don't see that Samba addon accepts secrets in its config file. 

So how do I go about using this?

**Comment by mrchief** [comment]
I spoke too early. While I still don't know the internals, it seems that adding the following in samba config actually works:

```
{
  "workgroup": "WORKGROUP",
  "username": "!secret samba_user",
  "password": "!secret samba_password",
...
```

Thanks for adding the support!

**Comment by CodeFinder2** [comment]
> I spoke too early. While I still don't know the internals, it seems that adding the following in samba config actually works:
> 
> ```
> {
>   "workgroup": "WORKGROUP",
>   "username": "!secret samba_user",
>   "password": "!secret samba_password",
> ...
> ```
> 
> Thanks for adding the support!

Yes, this is the correct way to go. 😉

**Comment by exup** [comment]
Hi, I am currently trying to do this in the samba addon, but wont allow it, I suspect I have some formating incorrtect. Could someone highlight my mistake

`Failed`` to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'workgroup': 'WORKGROUP', 'username': 'admin', 'password': '!secret samba_password', 'interface': '', 'allow_hosts': '- 10.0.0.0/8', '- 172.16.0.0/12': None, '- 192.168.0.0/16': None, "- 'fe80::/10'": None, 'veto_files': '- ._*', '- .DS_Store': None, '- Thumbs.db': None, '- icon?': None, '- .Trashes': ``None}`

`{
  "workgroup": "WORKGROUP",
  "username": "admin",
  "password": "!secret samba_password",
  "interface": "",
  "allow_hosts":
    "- 10.0.0.0/8",
    "- 172.16.0.0/12",
    "- 192.168.0.0/16",
    "- 'fe80::/10'",
  "veto_files":
    "- ._*",
    "- .DS_Store",
    "- Thumbs.db",
    "- icon?",
    "- .Trashes",
}`

**Comment by eloyvl** [comment]
It's perfect ... it works

**Comment by DanChaltiel** [comment]
It doesn't work anymore (in YAML):

```yaml
workgroup: WORKGROUP 
username: "!secret samba_username"
password: "!secret samba_password"
```

Chrome console tells me this:

`POST http://raspi.home:8123/api/hassio/addons/core_samba/options 400 (Bad Request)`

**Comment by CodeFinder2** [comment]
@DanChaltiel First, it's always important to report the version (HA, Supervisor, Samba addon) you are using. Second, I tested it (HA v2021.3.4, Supervisor v2021.03.6, Samba v9.3.1 - all latest as of now) and it was **still working fine for me**. Did you update your `secrets.yaml` AND restarted HA afterwards in order to make the changes take effect?

**Comment by eloyvl** [comment]
> Es perfecto ... funciona
But the message from Insecure secrets in core_samba keeps appearing:
Samba: 9.3.1
Core: 2021.3.4

**Comment by DanChaltiel** [comment]
@CodeFinder2 Oops, sorry! Indeed I didn't restart HA after changing secrets, thank you very much!
However, the console output was obviously related, as the message appeared whenever I hit the save button.

**Comment by Hohenloherin** [comment]
Didn't want to work, because I added a secret in my config.yaml. But this is creating an error. The solution I found here in post  1:
https://community.home-assistant.io/t/setup-failed-for-secrets-integration-not-found/187456
